project:
  title: "Atlas of Rutul dialects"
  output-dir: ./docs

website: 
  navbar:
    left:
      - text: "Features"
        icon: fa-atlas
        href: ./features.html
      - text: "Team"
        href: ./team.html
    right:
      - text: "Русский"
        href: ./ru/index.html

lang: en
